### ISSUE TITLE
Problems with Close-SqlConnection

### ISSUE THREAD

**Issue by mydomix** [mithrandyr/SimplySql#145]
Iam using 
`Open-OracleConnection -ConnectionName Work`
and everything is working fine. After iam closing the programm iam also closing the DB connection with 
`Close-SqlConnection -ConnectionName Work`
At sometimes i get response from the database (I got only 8 available sessions):
ORA-00018: maximum number of sessions exceeded

After this iam looking at 
`Show-SqlConnection -ConnectionName Work`
and nothing shows up. Is it possible that the connection isnt closed?

**Comment by mithrandyr** [comment]
@mydomix this might be related to [connection pooling](https://docs.oracle.com/en/database/oracle/oracle-database/19/odpnt/featConnecting.html#GUID-AAC5352A-83F2-483B-A681-93A5200CA83A).  Just because `Close-SqlConnection` closes and disposes the .NET connection object, doesn't meant the database does.

when you get that error, do you get it when trying to open another connection or is it a result of closing a connection?

**Comment by mydomix** [comment]
@mithrandyr yeah its if i try to open a new connection.

**Comment by mithrandyr** [comment]
Ok, as far as I can tell, this is related to Oracle itself and not the module.
