### ISSUE TITLE
Oracle LDAP Instruction

### ISSUE THREAD

**Issue by SOM-SPeters** [mithrandyr/SimplySql#47]
There are no examples of how to use a ldap lookup server for oracle connections.

**Comment by mithrandyr** [comment]
@SOM-SPeters  -- I'm not sure what exactly you are asking for.

**Comment by SOM-SPeters** [comment]
Instructions on connecting to an Oracle server via ldap.ora DIRECTORY_SERVERS, https://docs.oracle.com/cd/B28359_01/network.111/b28317/ldap.htm#NETRF362

**Comment by mithrandyr** [comment]
@SOM-SPeters  -- again I am still confused.  Are you wanting the documentation updated to with examples of using an LDAP lookup to connect to an oracle server?  Or are you saying there needs to be changes to the oracleProvider in the module to support this?

**Comment by SOM-SPeters** [comment]
It is either missing or not documented how to use a Oracle LDAP server to connect to the DB server.

**Comment by mithrandyr** [comment]
All the provider specific Open-*Connection support provider a connectionstring directly.  so you can use `Open-OracleConnection -ConnectionString "Oracle-LDAP Specific Connection String Here"` in order to open an oracle connection.

I have not (nor do I have any current plans) to provide greater support than this for Oracle LDAP connection scenarios.  The options I provide with named parameters are for standard scenarios, they are not meant to be comprehensive -- that is where the "-ConnectionString" parameter comes in.  If the provided options are not sufficient, then simply provide your own connectionstring.
