### ISSUE TITLE
Database connection in a PowerShell Job scriptBlock

### ISSUE THREAD

**Issue by AndreasNick** [mithrandyr/SimplySql#48]
We know the parameter -ArgumentList to transfer variables into a script block. Now I don't want to make a new connection every time in the script block. But I also don't know the variables in which the DB connection is stored. The parameter -ConnectionName does not work here either. How can a connection be passed on to a script block?

`Invoke-SqlQuery -Query "SELECT * FROM packageversions"

Start-Job -ScriptBlock {
  Invoke-SqlQuery -Query "SELECT * FROM packageversions"
  #ls c:\
} | Wait-Job | Receive-Job
`

**Comment by mithrandyr** [comment]
@AndreasNick  -- the cmdlet `Start-Job` actually launches an entire new powershell process (if you check task manager and/or get-process you will see it -- you can also run `$PID` inside a `Start-Job` scriptblock to see that its different from outside).
```powershell
#demonstrating that start-job is an entire new process...
$pid; Start-Job { $pid} | Receive-Job -AutoRemoveJob -Wait
```

Thus, nothing that exists in your powershell session will show up/be available in your job.

Lets ignore Jobs for the moment, and just deal with a regular powershell session where you need to query a database multiple times.
```powershell
Open-SqlConnection -SqlServer localhost -SqlDatabase someDb1
#you now have an open SQL connection, and its connection name is "Default", if you don't specify a connectionName for a command, then it will use "Default"

#Thus, the following two command are equivalent
Invoke-SqlQuery -query "Select * From someTable"
Invoke-SqlQuery -query "Select * From someTable" -ConnectionName "Default"

#you can keep using the various commands (invoke sql query/scalar/update, transactions, etc), when you are done, close the connection
Close-SqlConnection # this closes the default, or you can specify the connection directly: Close-SqlConnection -ConnectionName "Default"

#You can also have multiple connections open and use them. (they can refer to the same server/db, or something completely different, they are completely separate connections.
Open-SqlConnection -SqlServer localhost -SqlDatabase someDb1
Open-SqlConnection -SqlServer localhost -SqlDatabase someDb2 -ConnectionName "2nd"
Open-SqlConnection -SqlServer localhost -SqlDatabase someDb3 -ConnectionName "3rd"
Open-SqlConnection -SqlServer localhost -SqlDatabase someDb1 -ConnectionName "4th"

#to query against a connection other than "Default" (the first one, without a -ConnectionName) you will have to specify -ConnectionName for every command (in order to tell it which connection to use)

#quick way to close all open connections (the first command will return a list of ConnectionNames, the pipeline will send each one to Close-SqlConnection
Show-SqlConnection -All | Close-SqlConnection
```

Now, if you are using Start-Job because you want work to happen in the background, I would highly recommend you take a look at Start-ThreadJob -- its a light-weight approach (that uses background threads, rather that new OS processes).  However, the same principles apply, any functions, modules, variables, etc that you want in the background thread, has to be constructed/imported/etc into the background thread.
