### ISSUE TITLE
Unable to convert MySQL date/time value to System.DateTime

### ISSUE THREAD

**Issue by mikarosek5** [mithrandyr/SimplySql#69]
Hello,
PsVersionTable:
```
Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.14409.1018                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.14409.1018                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1
```

Select version():
`5.1.41-3ubuntu12`
The problem:
Some data fields has null value. 

When I query for a specific entry it works just fine (select * from tableName where id=1).
But if I query for all or subset (select * from tableName) I recieve error:

```
Exception calling "Fill" with "1" argument(s): "Unable to convert MySQL date/time value to System.DateTime"
At C:\Program Files\WindowsPowerShell\Modules\SimplySql\1.9.0\Providers\MySql\provider.ps1:42 char:13
+             $da.Fill($ds)
+             ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : MySqlConversionException
```

It is a bug or I doining somthing wrong?

Suggestion: add option to Open-MySQLConnection ConvertZeroDatetime=$true

With Regards

**Comment by mithrandyr** [comment]
@mikarosek5  -- take a look at this [SO Question](https://stackoverflow.com/questions/44754780/convert-zero-datetime-vs-allow-zero-datetime).  From my reading, if you have **zero** as a datetime value in MySQL, then its actual an error.  So the simplest solution would be to clean your data removing those values (setting them to a default value, minvalue or NULL depending upon the intent of the data element).  In terms of the querying -- if you can't update the data, then you need to transform it with your query.

```sql
SELECT --list of columns that work fine
    -- this CASE statement may not be doing the exact check, but something like it should work.
    , CASE dateColumn WHEN '0000-00-00 00:00:00' THEN NULL ELSE dateColumn END AS dateColumn
FROM someTable
```

Here is [another article ](https://bugs.mysql.com/bug.php?id=55425) that provides additional details.
Effectively, what you are experiencing is a value that MySql supports (actually its an error, but instead of preventing the record from being inserted/updated, it stores a ZERO to indicate an invalid value) that is not supported by C#.  The particular Connection Option you suggest adding is merely a bandaid with additional side-effects (see the 2nd article I linked).

I won't be adding this particular option to the **Open-MySQLConnection** cmdlet.  However, each of the Open-* cmdlets do support providing the connection string yourself, in which case you could pass this value.
